# Form implementation generated from reading ui file 'c:\Users\Sirichai\Desktop\chromedriver-win32\เรียนpy\week15\miniproject\light.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 352)
        Form.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Sirichai\\Desktop\\chromedriver-win32\\เรียนpy\\week15\\miniproject\\../../../../SHIDO.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("\n"
"\n"
"QWidget{\n"
"background-color:#0a0a0a;\n"
"color:white;\n"
"font-family:Nunito;\n"
"font-size:11pt;\n"
"}\n"
"\n"
"/* Neon Header */\n"
"\n"
"QLabel{\n"
"background:qlineargradient(\n"
"x1:0,y1:0,x2:1,y2:0,\n"
"stop:0 #00f2ff,\n"
"stop:1 #0077ff\n"
");\n"
"border-radius:6px;\n"
"padding:6px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"/* GroupBox Neon */\n"
"\n"
"QGroupBox{\n"
"border:2px solid #00eaff;\n"
"border-radius:12px;\n"
"margin-top:10px;\n"
"background:#111;\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"subcontrol-origin:margin;\n"
"left:10px;\n"
"padding:0 6px;\n"
"color:#00eaff;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"/* Table Dark */\n"
"\n"
"QTableWidget{\n"
"background:#0d0d0d;\n"
"gridline-color:#00eaff;\n"
"border:none;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background:#00aaff;\n"
"color:white;\n"
"border:none;\n"
"padding:5px;\n"
"}\n"
"\n"
"/* Button Base */\n"
"\n"
"QPushButton{\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"padding:6px;\n"
"}\n"
"\n"
"/* ON BUTTON */\n"
"\n"
"QPushButton#btn_on{\n"
"background:#00ff88;\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton#btn_on:hover{\n"
"background:#00ffaa;\n"
"}\n"
"\n"
"/* RESET BUTTON */\n"
"\n"
"QPushButton#btn_reset{\n"
"background:#ffaa00;\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton#btn_reset:hover{\n"
"background:#ffc933;\n"
"}\n"
"\n"
"/* OFF BUTTON */\n"
"\n"
"QPushButton#btn_off{\n"
"background:#ff3c3c;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton#btn_off:hover{\n"
"background:#ff5555;\n"
"}\n"
"\n"
"")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(60, 20, 421, 28))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 55, 421, 160))
        self.groupBox.setObjectName("groupBox")
        self.text_status = QtWidgets.QTableWidget(parent=self.groupBox)
        self.text_status.setGeometry(QtCore.QRect(10, 25, 401, 125))
        self.text_status.setObjectName("text_status")
        self.text_status.setColumnCount(4)
        self.text_status.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.text_status.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.text_status.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.text_status.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.text_status.setHorizontalHeaderItem(3, item)
        self.text_status.verticalHeader().setVisible(False)
        self.btn_on = QtWidgets.QPushButton(parent=Form)
        self.btn_on.setGeometry(QtCore.QRect(74, 260, 101, 41))
        self.btn_on.setObjectName("btn_on")
        self.btn_reset = QtWidgets.QPushButton(parent=Form)
        self.btn_reset.setGeometry(QtCore.QRect(215, 260, 101, 41))
        self.btn_reset.setObjectName("btn_reset")
        self.btn_off = QtWidgets.QPushButton(parent=Form)
        self.btn_off.setGeometry(QtCore.QRect(360, 260, 101, 41))
        self.btn_off.setObjectName("btn_off")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SHIDO API"))
        self.label.setText(_translate("Form", "ระบบเปิด-ปิด ไฟบ้าน"))
        self.groupBox.setTitle(_translate("Form", "STATUS"))
        item = self.text_status.horizontalHeaderItem(0)
        item.setText(_translate("Form", "No"))
        item = self.text_status.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Status"))
        item = self.text_status.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Day"))
        item = self.text_status.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Time"))
        self.btn_on.setText(_translate("Form", "ON"))
        self.btn_reset.setText(_translate("Form", "RESET"))
        self.btn_off.setText(_translate("Form", "OFF"))
        self.btn_off.setShortcut(_translate("Form", "Ctrl+Z"))
